### ISSUE TITLE
"Most Recent Activity" Formatting Issue

### ISSUE THREAD

**Issue by MohanMaker** [Aspine/aspine#144]
When first launching Aspine and when there are no recent activities, the formatting of the heading sections under "most recent activity" is messed up (it is minimized/you can't read the text). See the image below for more info. 
<img width="1410" alt="Screen Shot 2020-10-22 at 9 50 11 PM" src="https://user-images.githubusercontent.com/31443287/96947245-aa5db680-14b0-11eb-92d5-5f93eeaefc87.png">

**Comment by tektaxi** [comment]
Actually, at the beginning of this year, Aspen stopped reporting assignments as recent activity. We can just remove the recent assignments there unless we have our own way of calculating recents.

**Comment by MohanMaker** [comment]
Ok, I will look into how to calculate recents since this could be a useful feature to have. Otherwise, we can also just remove the recent section.

**Comment by tektaxi** [comment]
Yeah. The first thing that comes to mind to calculate recent assignments would be to take the first one (or few) assignments in each class and display them in recent activity. That would be instead of listing them by date added, because I don't think we actually have access to that date data now that aspen removed this feature. Idk if that helps but just what I thought of.

**Comment by psvenk** [comment]
This does sound like a good way to work around the problem of Aspen not showing the most recent assignments, and is anyway more flexible than relying on Aspen (because such things have happened in the past as well). Thank you @MohanMaker for opening the issue and thank you @tektaxi for responding so quickly!

**Comment by andOrlando** [comment]
Please tell me off if I shouldn't put this here but I think it's pretty related. Since the tabs are kind of clustered, what if we removed the recent tab and allowed you to unselect a class, in which case it would show the recent activity again.

**Comment by psvenk** [comment]
> Since the tabs are kind of clustered, what if we removed the recent tab and allowed you to unselect a class, in which case it would show the recent activity again.

@andOrlando I think showing the recent activity after unselecting a class would be a welcome addition. The original purpose of the recent tab (from my understanding) was that while one could see the most recent activity on the Grades tab, the Recent Activity tab gives older activity as well. One solution that @kdk1616, @Ruborcalor, and I had discussed in the spring is that we could collapse the tabs into a hamburger menu on smaller screen sizes (but this would merit a separate issue).

<details>
<summary>Screenshot of the navigation header taking up 4 rows on a 640x1136 mobile screen</summary>

![IMG_5226](https://user-images.githubusercontent.com/45520974/97084859-bc8e4080-15e7-11eb-9ca9-6a757d27d63c.PNG)

</details>
