### ISSUE TITLE
Add sidenav animation

### ISSUE THREAD

**Issue by MohanMaker** [Aspine/aspine#197]
Add an animation for when new items appear or disappear from the side menu (when you drag to change the size of the tab). We already have an animation for opening/closing the tab. See original pull request: #164

**Comment by andOrlando** [comment]
I can probably do this as the sidenav guy

**Comment by andOrlando** [comment]
by the way this is really hard unless we switch from moving the sidenav items to duplicating the sidenav items, in which case we'd have to rewrite the dropdown menus and some of the grade calculating code, since the dropdowns don't like to be in two places at once and I believe the grade calculating code replaces values in only a single dropdown or something
