### ISSUE TITLE
Categories and Assignments really hard to read on mobile

### ISSUE THREAD

**Issue by tektaxi** [Aspine/aspine#203]
On mobile, it's impossible to see the full name of an assignment or category with the current state of the table. We should reorganize it on small screens to be more readable. Maybe only display the name and category in the table, and click on the assignment for the score and more details? I'm not sure the specifics, but right now it's kind of a mess.

![IMG_65C06BC444EC-1](https://user-images.githubusercontent.com/45189395/101836142-d5f13a80-3b0a-11eb-8606-b54c63f9c7e8.jpeg)

**Comment by psvenk** [comment]
- Change the statistics modal so that it just opens below an assignment instead of being a modal
- Add more information to the statistics modal
- Remove this information from the row when on mobile so that the assignment name and percentage can be seen
- Show stats modal for assignments without statistics (#167)
- Load statistics lazily once the "info" is opened (so the stats loading does not block displaying the other information)
- When user clicks anywhere in the row on mobile, open the statistics/info box instead of editing name/score/etc.
  + Editing name/score/etc. can be moved down into the info box on mobile

**Comment by psvenk** [comment]
Partially addressed in #297. Additional tasks remaining, from <https://github.com/Aspine/aspine/pull/297#issuecomment-819933298>:

- [ ] Add category dropdown to stats modals on mobile
- [x] Adjust other tables (grades, categories, schedule) for mobile
- [x] Make the adjustments dynamic
- [x] Move info in stats modals to an expanded area in the assignments table
