### ISSUE TITLE
Assignment Feedback Integration

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#44]
Currently it is not possible to view assignment feedback from Aspine. I plan on adding assignment feedback to the modal that pops up when a student clicks the 🛈 icon for a given assignment.

**Comment by psvenk** [comment]
This seems like a good idea. It seems like this feature was added at some point but broke due to changes from Aspen, as the "Assignment Feedback" portion of the modal only contains my grade for the assignment (e.g. "98%98.5 / 100.0(A+)") and no feedback, even for assignments which show feedback on Aspen. It would be nice to indicate that an assignment has feedback (like on Aspen) and to show assignment feedback in classes which do not reveal statistics (as the modal just says "No Statistics Data for this assignment" in that case).

**Comment by Ruborcalor** [comment]
Ah good to know. I can work on fixing the assignment feedback scraping.

I guess it makes sense to give assignment feedback its own indicator and modal, and to only display the indicator when feedback is available.

**Comment by psvenk** [comment]
@Ruborcalor Ok, thank you. I did generalize some of the modal code in 0f90952782f7f6f3d44bf5041321b7548f1b5edc, so you may want to cherry-pick that commit.

**Comment by psvenk** [comment]
It would also be nice if the raw score, which is currently visible in the assignment feedback modal, were shown somewhere. Some teachers sometimes keep a raw score but store free text—in this case, the scraper assumes that the raw score is not useful unless a statistics request is made. It would be nice if we could store the raw score and the free text, with the client displaying only the free text by default but still keeping the raw score (so that it would be included in an export).
