### ISSUE TITLE
Aspine is broken

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#46]
Aspine seems to be broken due to a recent update. I tried signing in multiple times, from multiple devices, and I get redirected back to the login screen. I verified that my login is accurate because it works on Aspen.

On a slightly unrelated note, it would be nice if Aspine said “Wrong password” of the password is wrong, instead of just redirecting back to the login screen. This might have nothing to do with recent updates and may just be due to the fact that we are between Q3 and Q4.

**Comment by Ruborcalor** [comment]
#### The reason for the break is the following logic:

if(response.classes.length == 0) {
     location.href='/logout';
}

#### The former purpose of this logic
* To logout users when there is a problem with the /data request. 

#### The problem with this logic
* Aspen doesn't reveal classes until certain requirements are met.
* At the beginning of a new marking period no classes meet these requirements, so as far as Aspine is concerned the user trying to login has no classes.
* Therefore, the user is logged out despite entering their correct username and password.

#### The fix for this logic
* Use the http request response to decide whether or not a user should be logged out

#### Other ideas resulting from this issue
* Handle users without classes differently than users with classes. i.e. a "You Have No Classes" page.
* As psvenk said, let users know "Wrong Password" rather than a mysterious redirect

**Comment by Ruborcalor** [comment]
I have created a new branch, "improved_login", to resolve this issue.
