### ISSUE TITLE
Does not redirect to use HTTPS

### ISSUE THREAD

**Issue by 71c** [Aspine/aspine#85]
When I type aspine.us or http://aspine.us into the URL bar it does NOT redirect to use HTTPS. It does not redirect in Chrome and Safari but does redirect in Brave and Firefox on a Mac. It does not redirect on Chrome, Brave, Firefox, or Edge on a Windows computer. It does not redirect on Brave, Firefox, Chrome, or Safari on another Mac.

So basically it never redirects except for two funny exceptions.

Also...since I don't go to CRLS anymore my login doesn't work...is there any way I can get in because I'm curious?

**Comment by psvenk** [comment]
Thank you for the issue; I also noticed that and was alarmed. Displaying a warning or redirecting on a HTTP connection is on [the roadmap](https://github.com/Aspine/aspine/projects/2), but I'll add this issue to the roadmap instead of the stub note that I had added there.

Regarding the login issue: this will be solved by #79 (if I understand properly). There was a "fake" option on the server side to serve generic information, but it no longer works due to the refactoring for lazy loading (#77) that was required for fetching grades from other terms without losing too much performance (#81). #79 will likely be implemented differently from the "fake" option, with the choice of whether or not to use a test account being made on the client side instead of on the server side.

**Comment by Ruborcalor** [comment]
Thank you for opening this issue. My apologies for not thoroughly testing redirection. I use Firefox and on my manjaro direction http://aspine.us, http://www.aspine.us, and https://aspine.us redirected to https://www.aspine.us. 

I just modified the server configuration. On my computer all the above urls now successfully redirect to https://www.aspine.us with Chrome and Firefox.

It would be great if @71c could confirm that it redirects successfully on Mac and Windows with Chrome, Brave, Firefox, and Edge. Thanks!

**Comment by 71c** [comment]
Yeah, it redirects now everywhere.

Thanks, guys.

By the way I didn't bother looking for other issues and stuff; I'll check them out now.
