### ISSUE TITLE
Calculated grade doesn't match actual grade

### ISSUE THREAD

**Issue by extrarude** [Aspine/aspine#9]
I haven't added any assignments.
![image](https://user-images.githubusercontent.com/47579404/52674119-a06c6d80-2ef0-11e9-8edf-194e7b4be0b6.png)

**Comment by maxtkc** [comment]
Thanks for letting us know!

It is likely that this is because your teacher chose to change the grades in some way without displaying it on Aspen. Also, sometimes the teacher decides to have aspen disregard the section weights, and this can throw us off. Usually we guess at the grading system, but sometimes it can get it wrong.

Do you know if the class has any dropped assignments, grading idiosyncrasies, etc? If you wouldn't mind calculating your grade by hand to check against the real and the aspine calculated one, that would be fantastic!

**Comment by maxtkc** [comment]
Also, if your class has any assignments on the second page, then it won't show up. (We're fixing the second page issue now).

**Comment by maxtkc** [comment]
Our current fix is to get the best estimate and say that the calculated grade is the same (even if it's not), until the user changes something. It gives the best user experience, we think, even if it's not perfect. We're restricted by what Aspen gives it's users.
